### ISSUE TITLE
Default key-combo overwrites 'new line above'

### ISSUE THREAD

**Issue by benfrain** [jisaacks/MaxPane#9]
On OS X Sublime Text 3, here are the default key combination for super shift and enter:

`{ "keys": ["super+shift+enter"], "command": "run_macro_file", "args": {"file": "res://Packages/Default/Add Line Before.sublime-macro"} },`

Having installed MaxPane, it obviously overrides this. I've tried setting a user keymap:

`{ "keys": ["ctrl+shift+enter"], "command": "max_pane" }`

But now I get either of those key combos taking the pane to full screen. 

How should I be setting the key combo to invoke Max Pane so it doesn't interfere with existing key mappings?

**Comment by aicioara** [comment]
I solved my issue by adding these to my keymap

```
// Max Pane
{ "keys": ["alt+w"], "command": "max_pane" },
{ "keys": ["ctrl+shift+enter"], "command": "run_macro_file", "args": {"file": "res://Packages/Default/Add Line Before.sublime-macro"} },
```

**Comment by deathaxe** [comment]
All public releases of Sublime Text 3 beginning with build 3013 provide the following key bindings

```
	{ "keys": ["ctrl+k", "ctrl+left"], "command": "focus_neighboring_group", "args": {"forward": false} },
	{ "keys": ["ctrl+k", "ctrl+right"], "command": "focus_neighboring_group" },
	{ "keys": ["ctrl+k", "ctrl+shift+left"], "command": "move_to_neighboring_group", "args": {"forward": false} },
	{ "keys": ["ctrl+k", "ctrl+shift+right"], "command": "move_to_neighboring_group" },
```

The command `focus_neighboring_group` is equal to MaxPane's `shift_pane` and `unshift_pane` commands.

We should therefore change the key binding to ST's default ones for ST2 and disable `shift_pane` and `unshift_pane` for ST3.

**Comment by asumaran** [comment]
`ctrl + shift + enter` stopped working for me on Sublime Text 3. Did anything change?
